### ISSUE TITLE
[vite] Pre-transform error: Failed to load url $validations/feedbackValidationSchema (resolved id: /home/jason/projects/svelteprojects/baseKit/src/lib/validations/feedbackValidationSchema) in /home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts. Does the file exist?

### ISSUE THREAD

**Issue by jasonblewis** [edwardspresume/baseKit#1]
I followed the install instructions: clone the repo, pnpm install, pnpm dev, but I get this error:

```
jason@snow:~/projects/svelteprojects/baseKit$ pnpm dev

> base-kit@0.0.1 dev /home/jason/projects/svelteprojects/baseKit
> vite dev --host --open

12:30:34 pm [vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

@bobbymannino/svelte-progress@2.3.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
Forced re-optimization of dependencies

  VITE v5.2.7  ready in 1465 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://10.0.2.146:5173/
  ➜  Network: http://10.89.0.1:5173/
  ➜  press h + enter to show help
12:30:35 pm [vite] Pre-transform error: Failed to load url $validations/feedbackValidationSchema (resolved id: /home/jason/projects/svelteprojects/baseKit/src/lib/validations/feedbackValidationSchema) in /home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts. Does the file exist?
12:30:36 pm [vite] Error when evaluating SSR module /src/routes/+layout.server.ts: failed to import "$validations/feedbackValidationSchema"
|- Error: Cannot find module '$validations/feedbackValidationSchema' imported from '/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts'
    at nodeImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55037:25)
    at ssrImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:30)
    at eval (/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts:7:37)
    at async instantiateModule (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9)

Error: Cannot find module '$validations/feedbackValidationSchema' imported from '/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts'
    at nodeImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55037:25)
    at ssrImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:30)
    at eval (/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts:7:37)
    at async instantiateModule (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Cannot find module '$validations/feedbackValidationSchema' imported from '/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts'
    at nodeImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55037:25)
    at ssrImport (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:54946:30)
    at eval (/home/jason/projects/svelteprojects/baseKit/src/routes/+layout.server.ts:7:37)
    at async instantiateModule (file:///home/jason/projects/svelteprojects/baseKit/node_modules/.pnpm/vite@5.2.7_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:55006:9) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

**Comment by edwardspresume** [comment]
The issue was because I had changed the variable name from `FeedbackValidationSchema` to `FeedbackValidationZodSchema` and forgot to use the updated name for the import in `+layout.server.ts`

(I am still learning how to better name things 😅 but you can name it w.e you like)

Please me let know if run into any other issues

**Comment by digitalit** [comment]
Hi Edward,

Updated to Superforms 2.x.x and read that it was recommended to use valibot instead of zod.

Bein running valibot for a wile now and i really like it.

Any thoughts on this?

Have a nice day.
